from .manga import *
from .character import *
from .statistics import *
from .news import *
from .forum import *
from .pictures import *
from .recommendations import *
from .reviews import *
from .user_updates import *
from .relations import *
from .external import *
from .genre import *