name: Test anmoku

on:
  push:
  pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v4

        - name: Set up python3.9
          uses: actions/setup-python@v3
          with:
            python-version: '3.9'
        
        - name: Install dependencies
          run: pip install .[dev]
        
        - name: Run ruff and pytest
          run: |
           ruff check .
           pytest -v